Debugging

diff --git a/ec-slp/Dockerfile b/ec-slp/Dockerfile
--- a/ec-slp/Dockerfile
+++ b/ec-slp/Dockerfile
@@ -7,6 +7,10 @@ RUN wget https://github.com/simpleledger/Electron-Cash-SLP/archive/3.4.3.tar.gz
 RUN tar -xvf 3.4.3.tar.gz
 WORKDIR /home/safeuser/Electron-Cash-SLP-3.4.3
 
+# Install python dependencies.
+# Expect it to fail.
+RUN python3 setup.py install || echo "done"
+
 # Log in as the application user
 USER safeuser
 # supply password for sudo commands
